'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/provide-ai-suggestions.ts';
import '@/ai/flows/ensure-adsense-compliance.ts';
import '@/ai/flows/generate-blog-post-draft.ts';
import '@/ai/flows/generate-facebook-post.ts';
import '@/ai/flows/generate-youtube-script.ts';
import '@/ai/flows/generate-image-prompt.ts';
import '@/ai/flows/generate-image.ts';
import '@/ai/flows/generate-book-outline.ts';
import '@/ai/flows/generate-book-chapter.ts';
import '@/ai/flows/generate-book-marketing.ts';
import '@/ai/flows/generate-tweet.ts';
import '@/ai/flows/post-tweet.ts';
import '@/ai/flows/generate-and-post-tweet.ts';
import '@/ai/flows/scheduled-tweet-flow.ts';
import '@/ai/flows/scheduled-blog-post-flow.ts';
import '@/ai/flows/generate-chat-response.ts';
import '@/ai/flows/scheduled-facebook-post-flow.ts';
